version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "07:00"
    labels:
      - "dependencies"
    groups:
      pip-dependencies:
        patterns: [ "*" ]
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "07:00"
    groups:
      gh-actions-dependencies:
        patterns: [ "*" ]
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "07:00"
    groups:
      docker-dependencies:
        patterns: [ "*" ]