name: Build and publish

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  POETRY_VERSION: ${{ vars.POETRY_VERSION }}
  CONTAINER_REGISTRY: "${{ vars.CONTAINER_REGISTRY }}"
  CONTAINER_IMAGE: "${{ vars.CONTAINER_IMAGE }}"

jobs:
  variables:
    name: Set environment variables
    runs-on: ubuntu-latest
    container:
      image: python:3.12-alpine
    outputs:
      version: "${{ env.VERSION }}"
      version-major: "${{ env.VERSION_MAJOR }}"
      version-minor: "${{ env.VERSION_MINOR }}"
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install poetry
        run: pip install poetry==$POETRY_VERSION
      - name: Save version to environment
        run: |
          VERSION=$(poetry version -s)
          VERSION="${VERSION#[vV]}"
          VERSION_MAJOR="${VERSION%%\.*}"
          VERSION_MINOR="${VERSION#*.}"
          VERSION_MINOR="${VERSION_MINOR%.*}"
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "VERSION_MAJOR=$VERSION_MAJOR" >> "$GITHUB_ENV"
          echo "VERSION_MINOR=$VERSION_MINOR" >> "$GITHUB_ENV"
      - name: Display version
        run: echo "Version ${{ env.VERSION }}"
  build:
    name: Build images
    runs-on: ubuntu-latest
    needs: variables
    container:
      image: docker:20.10
    services:
      dind:
        image: docker:20.10-dind
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          tags: ${{ env.CONTAINER_IMAGE }}:latest,${{ env.CONTAINER_IMAGE }}:${{ needs.variables.outputs.version }},${{ env.CONTAINER_IMAGE }}:${{ needs.variables.outputs.version_major }},${{ env.CONTAINER_IMAGE }}:${{ needs.variables.outputs.version_major }}.${{ needs.variables.outputs.version_minor }}
  publish-docs:
    uses: ./.github/workflows/docs.yml

  create-release:
    name: Create release
    runs-on: ubuntu-latest
    needs: [ variables,build ]
    timeout-minutes: 5
    steps:
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ needs.variables.outputs.version }}
          tag_name: ${{ needs.variables.outputs.version }}
          target_commitish: ${{ github.sha }}
          generate_release_notes: true
